Hero
MarDak24/simplychocolate-group13 pull request #2
Opened 2023-03-17 18:21 UTC by anastasiialukianenko

2023-03-17 21:23 UTC, MarDak24 requested changes

2023-03-17 21:23 UTC, MarDak24 commented on src/css/hero.css
> +    max-width: 1200;
max-width: 1200px; та і впринципі якщо його прибрати - нічого не зміниться

2023-03-17 21:23 UTC, MarDak24 commented on src/css/hero.css
> +    background-color: var(--white-color);
Видалити  **background-color: var(--white-color);**, в base.css вже задано на body)

2023-03-17 21:23 UTC, MarDak24 commented on src/css/hero.css
> +font-family: 'Montserrat';
Видалити **font-family: 'Montserrat';**, задано в базових стилях

2023-03-17 21:23 UTC, MarDak24 commented on src/css/hero.css
> +.hero-btn{
Видалити в .hero-btn
text-align: center;
cursor: pointer;
font-family: inherit;
font-size: 14px;

2023-03-17 21:23 UTC, MarDak24 commented on src/css/hero.css
> +    background-color: transparent;
background-color: transparent; -  ні на що не впливає - можна видалити

2023-03-17 21:23 UTC, MarDak24 commented on src/css/hero.css
> +    margin-bottom: 32px;
Дублювання
Цей margin-bottom: 32px; вже задано на min 375px
тут можна видалити

2023-03-17 21:23 UTC, MarDak24 commented on src/css/hero.css
> +.hero-wrap {
flex та nowrap - ні на що не впливає, можна видалити

2023-03-17 21:23 UTC, MarDak24 commented on src/css/hero.css
> +
На таблет та десктоп інший розмір svg-scroll-down, тому потрібно додати сюди:

.scroll-down-icon {
width: 38px;
height: 38px;
}

2023-03-17 21:23 UTC, MarDak24 commented on src/css/hero.css
> +    .hero-title {
для .hero-title вже задано макс ширину в попередньому медіаправилі - тут можна видалити

2023-03-18 08:57 UTC, anastasiialukianenko commented on src/css/hero.css
> +    .hero-title {
зробила правки, виправила кнопку скрола, чекни будь ласка

2023-03-18 12:32 UTC, MarDak24 approved these changes

2023-03-18 12:32 UTC, merged